
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nygwbcsekdwrpjbpckmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55Z3diY3Nla2R3cnBqYnBja21qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTIwNTgsImV4cCI6MjA2MzM4ODA1OH0.i1bnHDPQ7VJK_sEONv2_RIx8IptBKLz-SY3qS0cHTyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to check if Supabase is properly configured with real values
export const isSupabaseConfigured = (): boolean => {
  return Boolean(SUPABASE_URL) && Boolean(SUPABASE_PUBLISHABLE_KEY) && 
         SUPABASE_URL !== 'https://placeholder-url.supabase.co' &&
         SUPABASE_PUBLISHABLE_KEY !== 'placeholder-key';
};
